AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This CloudFormation template creates a role assumed by CloudFormation
  during CRUDL operations to mutate resources on behalf of the customer.

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 8400
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: resources.cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - "connect:AssociateInstanceStorageConfig"
                - "connect:DescribeInstance"
                - "connect:DescribeInstanceStorageConfig"
                - "connect:DisassociateInstanceStorageConfig"
                - "connect:ListInstanceStorageConfigs"
                - "connect:UpdateInstanceStorageConfig"
                - "firehose:DescribeDeliveryStream"
                - "iam:PutRolePolicy"
                - "kinesis:DescribeStream"
                - "kms:CreateGrant"
                - "kms:DescribeKey"
                - "kms:RetireGrant"
                - "s3:GetBucketAcl"
                - "s3:GetBucketLocation"
                Resource: "*"
Outputs:
  ExecutionRoleArn:
    Value:
      Fn::GetAtt: ExecutionRole.Arn
